### ISSUE TITLE
AngleSharp Issue - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by vivekscripts** [mganss/HtmlSanitizer#107]
Hi,

I am htting this issues - https://github.com/AngleSharp/AngleSharp/issues/406 while I am using HTMLSanitizer. Looks like AngleSharp have fixed the issue in new version v0.10. Is HTMLSanitizer has integrated this change? I am hitting this issue in production more often. Appreciate your prompt reply.

**Comment by tiesont** [comment]
Current version is pinned at AngleSharp 0.9.9, so no.

**Comment by mganss** [comment]
AngleSharp v0.10 has not been released yet. I'll update as soon as it's available.

**Comment by vivekscripts** [comment]
checking back , has this been released? I continue to see issues in my code due to this :-(

**Comment by 304NotModified** [comment]
Well anglesharp still hasn't updated their package?

**Comment by 304NotModified** [comment]
See https://github.com/AngleSharp/AngleSharp/milestone/25

**Comment by dplaskon** [comment]
I believe this is fixed in the latest release - would it be possible to target AngleSharp 0.9.9.1?

https://github.com/AngleSharp/AngleSharp/issues/489

**Comment by mganss** [comment]
OK, I've released 4.0.183. Do you have a test case to verify this issue?

**Comment by dplaskon** [comment]
Unfortunately not as it was a threading issue that happened very rarely in production.

In either case -- thanks for the release! :)

**Comment by mganss** [comment]
OK closing this then.

**Comment by balee323** [comment]
documentText = "<img src=\"https: / blah/blah blah   png\" alt=\"\" width=\"640\" height=\"231\" class=\"aligncenter size-full wp-image-52735\" srcset=\"https: /t blah blah / p  ont nt/u lo d / 0  / 2/ r a ment-o -  T -  g s 1x.png 640w, https://   hracho.    n  jp/wp- on  nt/uplo   /    /02/     ment-of-    -  ges 1 -      8.png 300w, https:/  ec  a  o.  sin .j /wp-con en /upload /2  8   /  ea men -of-HT  -P  es  x  24  2 . ng 624w\" sizes=\"(max-width: 640px) 100vw, 640px\" />";


IHtmlDocument documentTextDom = new HtmlParser().Parse(documentText);

//This will cause an exception.  This text above is similar to some problem text i ran into in production.  My guess is all the crazy spaces and such kill parsing.  I rather the parser just skip this element and put in a message like "couldn't parse image tag"...   Instead i get that "Index was outside the bounds of the array" exception.     *** please don't delete this.  I hate when my comments get closed for no reason.  If I need to, I will open up a new ticket.

**Comment by tiesont** [comment]
@balee323 I don't see anywhere where you're using HtmlSanitizer. If your issue is due to AngleSharp, you need to raise it there.

**Comment by balee323** [comment]
@tiesont   - ahh thanks.  I think that's why my comments got deleted earlier.  thanks.  You can delete my off-topic comments.  Wished there was some sort of private messenger on github, but i see how that could be quickly abused.

**Comment by mganss** [comment]
@balee323 I don't delete comments 🤷‍♂️ I can't repro your problem using the latest version of HtmlSanitizer so probably updating will fix it. Regarding private messing, there's [Gitter](https://gitter.im).

**Comment by balee323** [comment]
@tiesont and @mganss  - thanks!  The problem is fixed (updated to latest version).  Thanks guys.

**Comment by piercy** [comment]
im still having this issue.  I'm using version 4.0.185. With anglesharp 0.9.9.1 (i had 3 projects using it, one of them was using 0.9.9 but its a seperate project from this issue).  I've upgraded them all to 0.9.9.2 and im going to see how that goes but as it can happen at any point im still very worried about this.


I dont know the in depth details of this issue, so im going to explain what we do and maybe you guys will tell me im being a moron and have to change.  Thats fine but i need to figure a solution as it was working for about a week in production,  then all of a sudden starts erroring for hundreds of people but still not categorically reproducible by us.


My application is a Angular web application that builds emails.  We send to and from the server in the form of JSON.  We coded HTMLSanitizer into our serialization.  So when we specify an attribute on a property, when the JsonConverter (Newtonsoft) does its thing, it runs our custom converter that at the same time sanitizes the string.   This essentially means for any properties we need to sanitize, we can specify an attribute and all sorted.  I have provided how we do this below.  

Any help or support on this would be highly appreciated.  

```csharp
using System;
using System.Linq;
using AngleSharp.Dom.Css;
using Ganss.XSS;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NLog;
using RestSharp.Contrib;


namespace GatorForms.Models.Serialization
{
    public class HtmlSanitizationSerializer : JsonConverter
    {
        public override bool CanWrite { get { return false; } }
        private static Logger _log = LogManager.GetCurrentClassLogger();

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            try
            {


                if (reader.Value == null)
                    return null;


                var sanitizer = new HtmlSanitizer();
                sanitizer.AllowedAttributes.Add("class");
                sanitizer.AllowedAttributes.Add("id");
                sanitizer.AllowedSchemes.Add("mailto");
                sanitizer.AllowedTags.Add("style");
                sanitizer.AllowedTags.Add("meta");
                sanitizer.AllowedAtRules.Add(CssRuleType.Media);
                sanitizer.RemovingComment += Sanitizer_RemovingComment;
                var safeString = sanitizer.Sanitize((string) reader.Value);

                return safeString;
            }
            catch (Exception e)
            {
                try
                {
                    _log.Error(e, "Sanitizer Error: " + (string) reader.Value);
                }
                catch (Exception e1)
                {
                    try
                    {
                        _log.Error(e1, "Sanitizer Error: Failed to write log.");
                    }
                    catch (Exception)
                    {
                    }

                }

                return (string) reader.Value;
            }
        }

        private void Sanitizer_RemovingComment(object sender, RemovingCommentEventArgs e)
        {
            var commentData = e.Comment.Data.ToLower();
            if (commentData.Contains("[if gte mso 9]") || commentData.Contains("[if mso]") || commentData.Contains("[endif]"))
                e.Cancel = true;
        }

        public override bool CanConvert(Type objectType)
        {
            return typeof(string).IsAssignableFrom(objectType);
        }
    }
}


```

**Comment by mganss** [comment]
@piercy If this still occurs with 0.9.9.2 please reopen AngleSharp/AngleSharp#406 as this is an issue within AngleSharp.

**Comment by 304NotModified** [comment]
offtopic:


@balee323 


I think I found your deleted comment ;) (https://github.com/AngleSharp/AngleSharp/issues/406)

![image](https://user-images.githubusercontent.com/5808377/38805148-170a078c-4175-11e8-8886-853e3e6a5fe0.png)
