### ISSUE TITLE
Add a strong name to nuget package

### ISSUE THREAD

**Issue by zerg32** [mganss/HtmlSanitizer#35]
Complied dll is missing a strong name so It is not possible to use it in strong named project.

Is it possible to add strong name during the build ?

**Comment by mganss** [comment]
The CsQuery NuGet package which HtmlSanitizer references is not signed, so unfortunately signing HtmlSanitizer doesn't seem to be possible currently.

**Comment by tiesont** [comment]
There's also: http://strongnamingconsideredharmful.com/

**Comment by 304NotModified** [comment]
Nice link :+1:

**Comment by 304NotModified** [comment]
Is this possible in v3?

**Comment by mganss** [comment]
I think so, AngleSharp seems to be strong named, see AngleSharp/AngleSharp#115.

**Comment by 304NotModified** [comment]
OK. I recommend to strong name it,  and only use the main version in the strong name. So the assembly version is for releases 3.0 - 3.x: `3.0.0` .  (iif we practice semver in the library)

**Comment by 304NotModified** [comment]
Edit: I don't think semver is used? Can that be arranged in version 3?

**Comment by mganss** [comment]
I very much like the automatic ".*" assembly versioning provided by [AssemblyVersionAttribute](https://msdn.microsoft.com/en-us/library/system.reflection.assemblyversionattribute.assemblyversionattribute.aspx). Not using this would mean we'd have to have some build script that does all kinds of versioning things (patch the assembly file version, set the NuGet version etc.).

**Comment by 304NotModified** [comment]
Well with `*` you get issues with strong naming, as described at http://strongnamingconsideredharmful.com/, and the version number is also not semver.

proposal:

- set fixed `AssemblyVersionAttribute` to `3.0.0.0` - from code or appveyor.yml
- before publish: change the `assembly_file_version` and `assembly_informational_version` (can be partly created by appveyor) - you can use variables. See https://github.com/NLog/NLog.Web/blob/master/appveyor.yml
- publish from appveyor after successful build

**Comment by mganss** [comment]
Done.

**Comment by Skybladev2** [comment]
@mganss I still do not see that NuGet package is signed, did you update it?

**Comment by mganss** [comment]
Only the beta is strong named (currently [3.1.67](https://www.nuget.org/packages/HtmlSanitizer/3.1.67-beta)).

**Comment by 304NotModified** [comment]
FYI strong looks good 

![image](https://cloud.githubusercontent.com/assets/5808377/11090548/01104756-8873-11e5-98fe-c065f2c3279f.png)

**Comment by 304NotModified** [comment]
@mganss why is the version updated to 3.1.x ? It that a test?

**Comment by mganss** [comment]
I had already published a NuGet package 3.0.5781.31354-beta before the move to SemVer.

**Comment by 304NotModified** [comment]
Mmmm

I think 3.1.67 is also not semver? I think it should be 3.1.0.67 or just 3.1.0. It's required to start with patch 0

**Comment by mganss** [comment]
Where does it say that?

**Comment by 304NotModified** [comment]
> Patch version MUST be reset to 0 when minor version is incremented.

7 on semver.org

**Comment by 304NotModified** [comment]
http://www.mememaker.net/static/images/memes/3769582.jpg

**Comment by mganss** [comment]
I can't see how that helps with the goals of SemVer. As long as the version number is strictly increasing  there shouldn't be a problem with specifiying dependencies.

**Comment by 304NotModified** [comment]
> I can't see how that helps with the goals of SemVer. As long as the version number is strictly increasing there shouldn't be a problem with specifiying dependencies.

I don't really understand what you mean. The choose is relative easy, HtmlSanitizer uses SemVer, or it doesn't.

If HtmlSanitizer is using SemVer (from 3.0?), then 3.1.0.67 is not allowed as an version number after 3.0.x.

**Comment by mganss** [comment]
OK, then it's "almost SemVer" :wink:

**Comment by 304NotModified** [comment]
That doesn't exist IMO. It the same like saying that IE6 sticks to the HTML standards. 

Why not unlisting the old packages and just create a 3.0 (-betaX) ?

**Comment by mganss** [comment]
I think the problem is not so much starting with SemVer at a specific version but rather resetting the third component to 0 (in the future). I don't see a way to achieve this and still use the automatic versioning provided by AppVeyor. It seems SemVer wasn't designed with CI in mind.

Also, there isn't a single browser w/o bugs :smile:

**Comment by mganss** [comment]
3.1.76 is strong named.
